-- 001_extensions.sql

CREATE SCHEMA IF NOT EXISTS asset;

CREATE SCHEMA IF NOT EXISTS audit;

CREATE SCHEMA IF NOT EXISTS common;

CREATE SCHEMA IF NOT EXISTS document;

CREATE SCHEMA IF NOT EXISTS incident;

CREATE SCHEMA IF NOT EXISTS infrastructure;

CREATE SCHEMA IF NOT EXISTS master;

CREATE SCHEMA IF NOT EXISTS security;

